Fix eks integration test failure
ansible-collections/amazon.cloud pull request #127
Opened 2024-07-24 18:00 UTC by GomathiselviS

##### SUMMARY

This PR fixes the failures seen in eks integration test suite.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2024-07-24 23:29 UTC, mandar242 commented on changelogs/fragments/fix_eks_tests.yml
> +- "Fix bugs in the eks integration tests."
```suggestion
- "Fix bugs in the eks integration tests."
```
```suggestion
- "Fix bugs in the eks integration tests (https://github.com/ansible-collections/amazon.cloud/pull/127)."
```

2024-07-25 00:07 UTC, mandar242 approved these changes
Tests are passing locally.

2024-07-25 15:19 UTC, abikouo requested changes

2024-07-29 14:13 UTC, abikouo approved these changes

2024-07-29 14:23 UTC, alinabuzachis approved these changes

2024-07-29 15:12 UTC, merged